package com.chriskormaris.mychessgame.api.enumeration;

public enum GameResult {
	NONE,

	WHITE_CHECKMATE,
	BLACK_CHECKMATE,

	WHITE_STALEMATE_DRAW,
	BLACK_STALEMATE_DRAW,

	INSUFFICIENT_MATERIAL_DRAW,
	CONDITIONAL_NO_CAPTURE_DRAW,
	UNCONDITIONAL_NO_CAPTURE_DRAW,
	THREEFOLD_REPETITION_DRAW,
	FIVEFOLD_REPETITION_DRAW,

	HORDE_NO_WHITE_PIECES_LEFT,
	HORDE_WHITE_STALEMATE_DRAW,

	// WIN_BY_RESIGNATION,
	// DRAW_BY_MUTUAL_AGREEMENT
}
